### ISSUE TITLE
LODO mailer

### ISSUE THREAD

**Issue by sls-lnluksa** [dodoas/lodo#101]
It seems that LODO mailer does not work.
Relating also to https://github.com/dodoas/lodo/pull/82.

Test if the mailer is set, and if there are some other methods that are using mailer.

**Comment by mladjo2505** [comment]
- In invoice.sendmail view, we send an invoice in the email both to the company and the specified address.
- In message class we have 2 methods that send emails, send_user() [used only in send_generic() method] and send_generic() [used in inc/support.php and inc/support.inc.php, which look the same, and that looks as a submit a question for support module]
- In inc/contact.php(or inc/contact.inc.php) as a contact us form.
  They all seem to be using the sendmail installation of the server which is used through mail() php function.

If something is not working, either it is a malformed mail() function call(some params may be not set correctly) or it has something to do with the installation/configuration of the sendmail server.

**Comment by sls-lnluksa** [comment]
@mladjo2505 Use some time to set it working locally. 
Try using your gmail account as smtp server.

**Comment by mladjo2505** [comment]
Tested and all seems to be working correctly.
If there are any errors I would say they are in the setup of the smtp on the server.

**Comment by agvald** [comment]
The lodo mailer seems to be working fine.
