### ISSUE TITLE
Work relations

### ISSUE THREAD

**Issue by mladjo2505** [dodoas/lodo#110]
- WR on salary edit page, remove other unnecessary fields.
- Work relation should replace the employee link in altinnReport1 and altinnReport1Employee tables.
- For one employee have a check that there are no WR for the same virksomhet at the same time.
- New DB table for WR and migrate old data.
- Remove old fields that are no longer needed in DB.
- Change report generating so it picks up WR not employee only.

This is what fields are needed for WR on employee.edit page(a row for each WR):

| Ansatt ved | Arbeid start | Arbeid slutt | Yrke | Samme posisjon siden | ... |
| --- | --- | --- | --- | --- | --- |
| < Virksomhet > | 0000-00-00 | 0000-00-00 | < Yrke > | 0000-00-00 | ... |

| ... | Arbeidstid | Skifttype | Ansettelsestype | Stillingsprosent | ... |
| --- | --- | --- | --- | --- | --- |
| ... | < Arbeidstid > | < Skifttype > | < Ansettelsestype > | % | ... |

| ... | Stillingsprosent oppdatert | Timer hver uke ved full stilling | Kommune |
| --- | --- | --- | --- |
| ... | 0000-00-00 | # | < Kommune > |

**Comment by mladjo2505** [comment]
@stoivo Look this over and see if we need to add/remove/change anything.

**Comment by mladjo2505** [comment]
- [x] New DB table for work relations
- [x] Migrate old data to new table
- [ ] If all data migrated sucessfuly, remove old fields(migration) (after successful deploy of WR, make new issue)
- [x] Table for all(at least one) WR on accountplan.employee page
- [x] Delete for each WR row action/button
- [x] Update/Save for all WR action/button
- [x] Add new WR action/button
- [x] Implement a check for all WR of one employee that they do not overlap for the same company 
- [x] Replace altinnReport1Employee employeeID foreign key with workRelationID foreign key (migrate employeeId to workRelationID)
- [x] Copy to salary fields from WR on salary.edit page and add one WR dropdown(based on virksomhet maybe? maybe some combobox with more info on WR?)
- [x] Change report class so the object/xml is built with WR instead of employee
- [x] Change link report and employees function to set WR_IDs instead of employee_IDs
- [x] Add checks so you always have a valid WR (start date < end date, required fields, etc..)
- [x] On altinnsalary.list page add employee and WR linked in the more info block
- [x] On altinnsalary.salarylist page show all employees and all of their WRs
- [ ] Possibly change the way salary.list page works/what it shows and how
- [ ] more...

**Comment by stoivo** [comment]
Looks like you have good coverage.

**Comment by stoivo** [comment]
We need Permitering as well
