### ISSUE TITLE
Add a separate button to save altinndato on salary edit page

### ISSUE THREAD

**Issue by mladjo2505** [dodoas/lodo#113]
Add one more button to salary edit page that is only going to save the altinndate for salary.
If the altindato is empty ('' or '0000-00-00') button is enabled and its action is to save the altinndato field only.
If the altindato is already set just show it as text, not as input and disable the button for saving it(unless the user is an administrator).

**Comment by stoivo** [comment]
Is this something we want?

**Comment by mladjo2505** [comment]
Arnt requested this.
