### ISSUE TITLE
salary.employeereport not showing employees when only one employee for some clients

### ISSUE THREAD

**Issue by hildegunn95** [dodoas/lodo#139]
Video: 2016-05-03_22-33-28-salary.employeereport_not_showing_employees-ID17769.mp4
db dump: 2016-05-03-salary.employeereport_not_showing_employees-ID17769.sql.zip

**Comment by mladjo2505** [comment]
by instructions from @hildegunn95 

![screen shot 2016-05-09 at 08 29 15](https://cloud.githubusercontent.com/assets/3684429/15105237/4a140606-15c0-11e6-9de4-2b396a0d461f.png)

"Utvalgskriterie er på grunnlag av altinndato på hver lønnsslipp"
translates to
"Selection criteria is based on altinn date on each paycheck"

![623e5f56-15c0-11e6-96f3-832cb8ff78be](https://cloud.githubusercontent.com/assets/3684429/15106106/41888924-15c7-11e6-9959-c97d5725d02f.png)
