### ISSUE TITLE
Add migration check table

### ISSUE THREAD

**Issue by mladjo2505** [dodoas/lodo#152]
We want to create a table to keep track of all migrations that were run on each DB and the statuses of those.

The structure of the table:

| MigrationID | MigrationName | Status | StartedAt | SucceededAt |
| --- | --- | --- | --- | --- |
| # | path/to/migration_file.sql | STARTED/OK | 21:04:54 | 22:12:56 |

**_Important**_
After adding this table, each migration should have an insert query at the top and an update query at the bottom(or added automatically to migration logic). 
First is to add to the migration table an entry with status started, letting us know that the migration has started.
The second is to update(for the same row we inserted at the beginning) status to ok at the end, letting us know that everything has been run correctly.
That way we could check which migrations have been successfully run on each DB and possibly if there were some migrations that failed.

Add an additional simple view that lists the migrations that have been run (either successfully or unsuccessfully) also.

**Comment by stoivo** [comment]
One example

``` sql
INSERT INTO Migrations (MigrationID, MigrationName, Status, StartedAt) 
VALUES (1, "001_example", "STARTED", NOW())

-- the "normal" migration should be here

UPDATE Migrations
SET Status = 'OK', SucceededAt = NOW()
WHERE MigrationName = '001_example';
```

Not sure if this is the correct names.

**Comment by stoivo** [comment]
Maybe we can change batch.php so this will be added automatically when the migration is run? 
This require some more investigation but I this is is worth spending some time on.
