### ISSUE TITLE
Understand how voucher's vat lines is managed

### ISSUE THREAD

**Issue by agvald** [dodoas/lodo#211]
Vat lines lose connection to main line when switching between different balanse and resultat fast.

**Comment by sls-lnluksa** [comment]
Possible connected to #287

**Comment by agvald** [comment]
We should investigate why vouchers take so long to save on the Lincoln-Pub DB, possibly create a separate issue for this.

**Comment by mladjo2505** [comment]
Hanging VAT lines caused by Fast switching of account on journal.edit page.
Issue recreated multiple times by @hildegunn95
