### ISSUE TITLE
Save in Lodo when we sent AGA and FRT to fakturabank

### ISSUE THREAD

**Issue by stoivo** [dodoas/lodo#218]
Save these values with user id and timestamp.

The send button should work even if you already sent in once. Overwrite the the user id and timestamp

**Comment by Baxxx** [comment]
Discuss how to save and where.

**Comment by stoivo** [comment]
I this we can add two columns to altinnReport4, SentToFakturabankAt and SentToFakturabankBy.

Some thoughts ?

**Comment by Baxxx** [comment]
This seems valid.
