### ISSUE TITLE
Old voucher saved to new period should show in MVA report

### ISSUE THREAD

**Issue by mladjo2505** [dodoas/lodo#223]
If we bookkeep a voucher with an old VAT percent (ex. 24%) and save it in the period that VAT percentage is not valid anymore, the MVA report should show an additional column for that specific voucher and have the account and percent for the old VAT percentage.

@hildegunn95 Maybe add a db dump to provide additional information.

**Comment by hildegunn95** [comment]
db dump: 2016-07-28-MVA_report_with_an_old_MVA_kode.sql.zip
