### ISSUE TITLE
Improve fetch information for company from fakturaBank

### ISSUE THREAD

**Issue by mladjo2505** [dodoas/lodo#231]
When updating customer/supplier info from fakturaBank some fields are being overwritten. Only change to ones that are received from fakturaBank and are not empty.

**Comment by Baxxx** [comment]
Updating the account plan information based on information from FB doesn't work correctly (the page messes up when trying to update non-norwegian customer/supplier).

**Comment by Baxxx** [comment]
Kredit tekst and debit tekst fields lose color and value when you create new firmaID on just created supplier/customer.

**Comment by hildegunn95** [comment]
Video: Lodo/2016-09-14-fetch_info_based_on_firmaID.mp4
