### ISSUE TITLE
Creating suppliers from invoice incoming import page not creating FirmaID

### ISSUE THREAD

**Issue by mladjo2505** [dodoas/lodo#237]
When we create the missing suppliers from the incoming invoices import page they should be created with at least the FirmaID they are detected with in the import page, for example NO:ORGNR or whichever one is sent by fakturaBank.

To reproduce the issue you should mark some of the incoming invoices as for bookkeeping on fakturaBank for some of the suppliers that are not in the current companies database(or delete a supplier of the invoice) try to import them on `Innkommende fakturaer>Importer fakturaer med status regnskapbilag fra Fakturabank`. On that page there should be listed all the invoices marked for bookkeeping in fakturaBank for that company and there should also be input fields for some info about suppliers for the ones that are missing in the db. The button labeled with `Opprett manglende kontoplaner (A)` should create all the missing suppliers with the info you entered on that page. The newly created suppliers should have at least one FirmaID created for them.

**Comment by Baxxx** [comment]
Updating the account plan information based on information from FB doesn't work correctly.
