### ISSUE TITLE
Alinn salary export rights

### ISSUE THREAD

**Issue by hildegunn95** [dodoas/lodo#246]
Video: Lodo/2016-08-25-altinn_salary_export.mp4

**Comment by mladjo2505** [comment]
Waiting for db dump and video of the reproduced error.

**Comment by stoivo** [comment]
@mladjo2505, have you got what you need?

**Comment by mladjo2505** [comment]
Not until @hildegunn95 tells me what I should do.

**Comment by hildegunn95** [comment]
This  will be done on FB side, the issue is not valid anymore, it should be closed. @stoivo

**Comment by stoivo** [comment]
Issue 402 in fakturabank
