### ISSUE TITLE
invoice rabatt on lines and invoice rabatt total

### ISSUE THREAD

**Issue by agvald** [dodoas/lodo#257]
This has been integrated in FB

The following point is locations where rabatt should be implemented 
- [x] Creating outgoing invoices
- [x] Sending invoices to FB
- [x] Importing outgoing invoices from FB
- [x] Importing Incoming invoices from FB

**Comment by mladjo2505** [comment]
Re-estimated due to unforeseen troubles with FB allowance charge creation(Needs to be done manually in DB/Rails console) on invoice.
