### ISSUE TITLE
Spaces removed from firmaID value when saving firmaID

### ISSUE THREAD

**Issue by Baxxx** [dodoas/lodo#264]
On saving firmaID, not all of the scheme values should be formatted like this (`str_replace ' ' with ''`). Phone number for example can be set as '123 45 678', and wont work if formatted to '12345678'

**Comment by mladjo2505** [comment]
What about #243 ?

**Comment by Baxxx** [comment]
Or rework FB so it works with such trimmed values?

**Comment by stoivo** [comment]
We should remove all spaces from firma id in lodo and fakturabank

**Comment by stoivo** [comment]
I mean that we should clean db fields

**Comment by stoivo** [comment]
Will be fixed in fakturabank in issue 382

**Comment by Baxxx** [comment]
Good, we can close this.

**Comment by stoivo** [comment]
We still need to strip spaces from existing in  lodo. Is that done?
