### ISSUE TITLE
Creating new client

### ISSUE THREAD

**Issue by hildegunn95** [dodoas/lodo#283]
Company info
- [x] 'Firma' -> 'Firmanavn'
- [x] 'Telefon' -> 'Firmatelefon'
- [x] add 'Firma-epost', save this value to company info(company.edit), in contact info, unit email. 

Person info
- [x] 'Mobil' -> 'Privat telefon'
- [x] 'Email' -> 'Privat epost'
- [x] 'Bekreft Email' -> 'Bekreft privat epost'

**Comment by stoivo** [comment]
- [x] Remove change to not have vat
