### ISSUE TITLE
Downloading foreign currency invoices

### ISSUE THREAD

**Issue by mladjo2505** [dodoas/lodo#290]
When downloading foreign currency invoices, the amount that gets converted to local currency should go to the supplier/customer, and the difference from the actual paid amount from bank transaction should go to the motkonto result accountplan for that supplier/customer.

**Comment by hildegunn95** [comment]
See pdf for example of voucher.
Want to select currency and rate for each voucher line. 
If you select currency it the top row, and hit save, you will auto fill the other lines. These lines can be changed manually later. It's important that debet+kredit=0. If not, create a voucher line with the difference. Main thing is that sum on debet+kredit=0 on NOK, currency sum may be different than 0 due some rounding and differences in rate.
How to calculate amount and rate: First debet-kredit(1), then currency(2), then rate(3). If 1 and 2 are filled, do calculate 3. If 1 and 3 are filled, do calculate 2. If 2 and 3 are filled, do calculate 1. If all three are filled, recalculate 3(rate). 
These fields about currency in voucher line level are only visible if currency different than NOK is selected(and saved) in the top row. 
This is for all types of vouchers.
[currency-voucher.pdf](https://github.com/dodoas/lodo/files/602257/currency-voucher.pdf)

**Comment by sls-lnluksa** [comment]
Discussed with Arnt about solution for this task.
