### ISSUE TITLE
Postmotpost further speedup

### ISSUE THREAD

**Issue by mladjo2505** [dodoas/lodo#342]
The first idea is to change the way we store how the vouchers are matched, and by changing that we make it easier to collect which vouchers are matched and which ones aren't.
The ones that are matched could get a new column in the voucher table. Something like match_group_name as a string that would be a hash defining what are the things matched in this group(for example "INVOICENO-306" specifies that the vouchers matched in this group are ones with Invoice number 306).
Making this would require adding a column to the voucher struct table for match_group_name in the first part of the migration and populating it as best we can with the existing data on how the vouchers were matched. On the ones that we cannot figure out how they were matched we can, in the second part of the migration specify a hash consisting of their voucher ids. The third part of the migration would be moving the column match_group_name into voucher table and destroying the voucher struct which is no longer gonna be needed.
After this we can easily fetch what other vouchers were matched (if any) with the current one we are processing and also easily fetch the non-matched ones. Also with a little aggregate function and grouping(by invoice number, kid or match number) in sql we will get the possible matches for the open vouchers(for example sum the amount by groups on invoice number and if the sum is 0 we have a possible match).
Need to discuss after some research what the best approach would be.

**Comment by mladjo2505** [comment]
It was agreed by ( @stoivo @sls-lnluksa @Baxxx and me ) to go with this idea.
Additional things:
- Try to merge the tables voucherstruct and vouchermatch into the voucher table
- Instead of match_group_name being a hash of type string, make it a foreign key of type integer to a additional reconciliation info table
- match_group_name as integer has to be unique to each new group(some logic there)
- The additional reconciliation info table will hold stuff like created_at, created_by, ...

**Comment by stoivo** [comment]
Table structure

voucher                        

id  | amount     | invoiceno  | matched_by | kid | matchtext | Voucher reconciliation id
--- | ---        | ---        | ---        | --- | ---       | ---
1   | 100        | 12         | invoice    |     |           | 1
2   | -50        | 12         | invoice    |     |           | 1
3   | -50        | 12         | invoice    |     |           | 1
4   | -123       | 12         |            | 541 | todo      | 2
5   | 123        | 41         | match      | 143 | todo      | 2


voucher_reconciliation      old name: vouchermatch  and voucherstruct          

id  | created at | created by
--- | ---        | ---
1   | 12:30      | Simon
2   | 14:21      | Simon
