### ISSUE TITLE
PDF invoice view proposal

### ISSUE THREAD

**Issue by mladjo2505** [dodoas/lodo#346]
### Proposal number 1:

- [x] Have highlight on a/c lines, but no highlight on invoice lines
- [x] Remove the delimiter line between invoice lines
- [x] Print delimiter only after a/c for invoice line if any

### Proposal number 2:

- [x] Have highlight on a/c lines, but no highlight on invoice lines
- [x] Do not print delimiter between a/c for invoice line and the invoice line

### Proposal number 3:

- [x] Have no highlight on invoice lines or a/c
- [x] Do not print delimiter anywhere between a/c and invoice line

### Proposal number 4:

- [x] Have no highlight on invoice lines or a/c
- [x] Print delimiter between a/c for invoice line and next  invoice line
- [x] Do not print delimiter anywhere between a/c and invoice line
- [x] Print invoice no with big font like 'Faktura' above where it is located now 

### Proposal number 5:

- [x] Copy stage 4
- [x] Remove grey background from Leverigsagress (delivery)
- [x] Reduce the delimiter between a/c for invoice line and next  invoice line to only underline Produktnavn (product name)

**Comment by mladjo2505** [comment]
_Proposal number 1_ on branch **pdf_proposal_1**
_Proposal number 2_ on branch **pdf_proposal_2**
_Proposal number 3_ on branch **pdf_proposal_3**
_Proposal number 4_ on branch **pdf_proposal_4**
_Proposal number 5_ on branch **pdf_proposal_5**

**Comment by stoivo** [comment]
There is a mistake in Proposal 1 and Proposal 2
![screen shot 2016-12-23 at 08 10 32](https://cloud.githubusercontent.com/assets/3492040/21448850/5caa8a80-c8e7-11e6-81b8-cb893f3d9ea4.png)

**Comment by mladjo2505** [comment]
The issue with lines overlapping the totals was not only on the pdf proposal branches but the master as well. Seems if you add a customer comment to the invoice it gets printed and it moves the invoice line header lower but it does not reduce the number of lines per page by the number of lines the customer comment takes up. Fixed on all proposal branches.

**Comment by stoivo** [comment]
Good, I added Proposal number 4

**Comment by stoivo** [comment]
I added Proposal number 5

**Comment by mladjo2505** [comment]
We decided to use proposal number 5.
@stoivo Other branches can be deleted?
I will make a pull request for proposal number 5.

**Comment by stoivo** [comment]
Yes. I will do it now.
