### ISSUE TITLE
Currency preselected for supplier makes trouble in journal.edit + punching of currency

### ISSUE THREAD

**Issue by hildegunn95** [dodoas/lodo#349]
- [x] When currency is preselected for the supplier are debet and credit fields in journal.edit disabled. 
They should not be disabled. 
- [x] In journal.edit, if the supplier has preselected currency, do show this currency immediately if supplier is selected. If the voucher already has some currency, do not edit this, else recalculate currency for default. 
- [x] Do always print both credit and debit currency fields, when currency is selected.

**Comment by hildegunn95** [comment]
Invoice no and KID were not working correctly, so they had to change something in the code to make it work. I believe that made this currency selection not work. If you select a currency and hit 'save', you'll lose all entered data, and it will reset to default values. 
Video: Lodo/2017-01-05-currency_select

Logic made in #290

**Comment by Baxxx** [comment]
Video transcribed:

- [x] Remove top selection for currency. Always display the currency selection on every voucher.
- [x] When something else than NOK is selected as the currency, display both currency in and out fields, populating the correct one upon save.
- [x] Currency in and out should work the same way as voucher in and out regarding the functionality of splitting the voucher into two lines.
- [x] Move save button all the way to the left, even in front of double arrows.
- [x] Remove Saldo column.
- [x] Change the order of `Department, Project, Car` to `Car, Project, Department`

**Comment by Baxxx** [comment]
- [x] Save button appears on both left and right side on new journal. Should not.
- [x] For bank vouchers when changing supplier select it's default currency if no currency is selected.
