### ISSUE TITLE
Bookkeep incoming invoices working slowly

### ISSUE THREAD

**Issue by hildegunn95** [dodoas/lodo#357]
action_invoicein_journal works really slowly. 
Try to bookkeep 40 invoices at once.

**Comment by mladjo2505** [comment]
@hildegunn95:
After extensive testing, the only thing that takes a long time to do is downloading the invoices from fb. And that is only if some of them are from new(unknown) suppliers, so we have to wait on fb to fetch the supplier info from brreg.no, which slows the downloading significantly.
It would be nice to talk about this a little and get a good db dump as well as an example that recreates the issue.

**Comment by stoivo** [comment]
Why do we fetch from brreg? Doesn't that information already exist in fb?

**Comment by mladjo2505** [comment]
Do not know. We should check in fb code or in the example.

**Comment by sls-lnluksa** [comment]
After discussion with Arnt Telhaug:
We decided to fetch data only from FB. Fetch from Brreg only if company does not exist in FB.
If company does not exist in FB, also create it there.
