### ISSUE TITLE
Automatically select default project - journal.edit

### ISSUE THREAD

**Issue by hildegunn95** [dodoas/lodo#358]
Bookkeeping to an account with default project should select the project automatically.

Example: If you download an invoice where supplier has default result account 4001. And result account 4001 has default project 123. When you bookkeep the invoice, project 123 should be selected since it's default for account 4001.
Same goes for department and car, unless it(project/department/car) is already selected(downloaded from fb).

**Comment by mladjo2505** [comment]
After discussion with Arnt we came to this:

- [x] For incoming invoices:

When sending the Project/Department/Car(P/D/C) in an incoming invoice from FB save that value no matter what. If not, then save the default from supplier's result account plan if it is enabled, else save nothing. Ignore settings for P/D/C on supplier.

- [x] For outgoing invoices:

When sending the P/D/C in an outgoing invoice from FB save that value no matter what. If not, then save the default from product's result account plan if it is enabled, else save nothing. Ignore settings for P/D/C on customer and product.
(**EDIT**: After implementing this same logic for outgoing as for incoming we decided that there is no need for that, so we only save what is on product if anything is enabled there)

- [x] Extra comment:

If there is a value saved on a voucher for P/D/C and for it's account plan the P/D/C is disabled it does not show. Just display the info(as plain text) if disabled and set in DB.
(**EDIT**: Show if set in db for invoicein lines as well)
Ignore all P/D/C stuff for supplier/customer voucher(voucher head).
