### ISSUE TITLE
Incorrectly bookkept outgoing voucher

### ISSUE THREAD

**Issue by mladjo2505** [dodoas/lodo#421]
When we send 0% VAT products from FB and have the same products with 25% VAT in LODO something is not bookkept correctly.

**Comment by mladjo2505** [comment]
The problem is occurring in `invoice.class.php` in method `set_line()` [here](https://github.com/dodoas/lodo/blob/7258ab01e2ea6cfb2a5d97d620b31ccf8ea9a989/modules/invoice/model/invoice.class.php#L825)

There we are assigning the account's VatID to line instead of using the VatPercent we have on the line.

**Comment by mladjo2505** [comment]
@stoivo What is happening with this?

**Comment by sls-lnluksa** [comment]
After discussion with Arnt:
This issue is human error. We don't need to fix anything. Product accountplan is wrong.
