### ISSUE TITLE
Can't send outgoing invoice from lodo to fakturaBank

### ISSUE THREAD

**Issue by hildegunn95** [dodoas/lodo#483]
Outgoing invoice S11246, try to send to fakturabank. 
Error: Unable to autoload constant XMLReaderBase, expected /var/www/apps/fakturabank/releases/20170421075251/lib/invoice_xml/xml_reader_base.rb to define it 
DB: Lodo/2017-04-22-cant_export_S11246.sql.zip

**Comment by stoivo** [comment]
Fixed in FB
