### ISSUE TITLE
Import bank balance amount and pick up first voucher number

### ISSUE THREAD

**Issue by hildegunn95** [dodoas/lodo#50]
When importing bank transactions from FakturaBank the start and end amounts should be saved for bank balance and if they are not set before, overwrite them. If the bilagsnr is set use it for the bank transactions(already working). 

Add save button for balance amount for bank transactions, and an additional one for the starting voucher number. When the balance has been saved once, it should not be overwritten by imported data from FB.

**Comment by stoivo** [comment]
I suggest to make it update the start and end amount when importing from fakturabank. And overwrite the current saved values if it is 0,00 or blank or not saved.
