### ISSUE TITLE
Locked salary and altinn related fields

### ISSUE THREAD

**Issue by mladjo2505** [dodoas/lodo#69]
- [x] After the salary is locked, a regular user can't change the altinn related fields but an admin still can.
  Figure out why and allow this.
- [x] Add the Reported to Altinn date to salary.edit page.
- [x] Add Altinn date and reported to altinn date to the salary.list

**Comment by mladjo2505** [comment]
Related to issue #110
Should only do #113 
See if something needs to be done after both of the above issues are resolved.

**Comment by stoivo** [comment]
This is not the behavior we want to have. 
Behavior for accesslevel 2: (kunde)
Can open the salary and change it as long as it is open. The user should be able to Only save altinn related fields without updating the timestamps(the save button you made here already). 
When the user want to lock the salary we should check if these five altinn fields a there. If any of the fields are missing, inform the user and ask if the user want to lock anyway.

Behavior for accesslevel 4: (admin)
All fields are editable and can be saved. We should show the button to only save altinn related fields like we do if the salary is not locked for a user with accesslevel 2.
