### ISSUE TITLE
New yearly salary report for altinn reported salaries

### ISSUE THREAD

**Issue by mladjo2505** [dodoas/lodo#71]
Create a new report for salaries similar to arbeidsgiveravgift.inberarbeidsgiveravgift only instead of termins use each month of the year.

**Comment by stoivo** [comment]
Consult with Arnt and make a XLS sheet how it should look.

**Comment by mladjo2505** [comment]
@stoivo or @hildegunn95
Ask Arnt if he has the time to prepare an XLS file of how this report should look like.
Without that this task is on hold.

**Comment by mladjo2505** [comment]
Any new info on this?
It's been almost 3 months!

**Comment by sls-lnluksa** [comment]
Talked with Arnt 2016-12-07.
We need XLS file to continue with this task.

**Comment by mladjo2505** [comment]
@hildegunn95 has created the excel sheet for this report.

**Comment by hildegunn95** [comment]
Excel file: Lodo/2016-12-13-Altinn_AGA_FTR.ods
